const fs = require('fs');
const s = fs.readFileSync('ohio-cities.js', 'utf8');
const m = s.match(/window\.OHIO_PLACES\s*=\s*(\[[\s\S]*?\]);/);
const arr = eval('(' + m[1] + ')');
const seen = new Set();
const uniq = [];
for (const p of arr) {
  const k = p.n.toLowerCase();
  if (!seen.has(k)) { seen.add(k); uniq.push(p); }
}
uniq.sort((a, b) => a.n.toLowerCase() < b.n.toLowerCase() ? -1 : a.n.toLowerCase() > b.n.toLowerCase() ? 1 : 0);
const header =
  '/* Auto-generated by build-ohio-cities.js — do not edit by hand.\n' +
  ' * Ohio cities + county centroids with coordinates, used to place calls on\n' +
  ' * the map by matching city/county names inside talkgroup titles.\n' +
  ' * Source: kelvins/US-Cities-Database (MIT). ' + uniq.length + ' cities, 88 counties.\n' +
  ' */\n';
let body = 'window.OHIO_PLACES = [\n';
for (const p of uniq) {
  body += '  { n: "' + p.n + '", la: ' + p.la + ', lo: ' + p.lo + ' },\n';
}
body = body.replace(/,\n$/, '\n');
body += '];';
fs.writeFileSync('ohio-cities.js', header + body + '\n');
console.log('written', uniq.length, 'entries');
